version: '3.8'

services:
  up-to-ynab-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: up-to-ynab-dev
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DEBUG_MODE=true
      - UP_API_TOKEN=${UP_API_TOKEN}
      - UP_BASE_URL=https://api.up.com.au/api/v1/
      - WEBHOOK_URL=${WEBHOOK_URL}
      - YNAB_API_TOKEN=${YNAB_API_TOKEN}
      - YNAB_BUDGET_ID=${YNAB_BUDGET_ID}
      - YNAB_ACCOUNT_ID=${YNAB_ACCOUNT_ID}
      - YNAB_BASE_URL=https://api.youneedabudget.com/v1/
      - DATABASE_URL=sqlite+aiosqlite:///./data/up_to_ynab.db
    volumes:
      - .:/app
      - ./data:/app/data
    networks:
      - up-to-ynab-dev

networks:
  up-to-ynab-dev:
    driver: bridge